package com.eu.habbo.habbohotel.wired;

public enum WiredEffectType {
    TOGGLE_STATE(0),
    RESET_TIMERS(1),
    MATCH_SSHOT(3),
    MOVE_ROTATE(4),
    GIVE_SCORE(6),
    SHOW_MESSAGE(7),
    TELEPORT(8),
    JOIN_TEAM(9),
    LEAVE_TEAM(10),
    CHASE(11),
    FLEE(12),
    MOVE_DIRECTION(13),
    GIVE_SCORE_TEAM(14),
    TOGGLE_RANDOM(15),
    MOVE_FURNI_TO(16),
    GIVE_REWARD(17),
    CALL_STACKS(18),
    KICK_USER(19),
    MUTE_TRIGGER(20),
    BOT_TELEPORT(21),
    BOT_MOVE(22),
    BOT_TALK(23),
    BOT_GIVE_HANDITEM(24),
    BOT_FOLLOW_AVATAR(25),
    BOT_CLOTHES(26),
    BOT_TALK_TO_AVATAR(27),
    FURNI_AREA_SELECTOR(28),
    FURNI_NEIGHBORHOOD_SELECTOR(29),
    FURNI_BYTYPE_SELECTOR(30),
    USERS_AREA_SELECTOR(31),
    USERS_NEIGHBORHOOD_SELECTOR(32),
    SEND_SIGNAL(33),
    FREEZE(34),
    UNFREEZE(35),
    FURNI_TO_USER(36),
    USER_TO_FURNI(37),
    FURNI_TO_FURNI(38),
    SET_ALTITUDE(39),
    RELATIVE_MOVE(40),
    CONTROL_CLOCK(41),
    ADJUST_CLOCK(42),
    MOVE_ROTATE_USER(43),
    FURNI_ALTITUDE_SELECTOR(44),
    FURNI_ON_FURNI_SELECTOR(45),
    FURNI_PICKS_SELECTOR(46),
    FURNI_SIGNAL_SELECTOR(47),
    USERS_SIGNAL_SELECTOR(48),
    USERS_BY_TYPE_SELECTOR(49),
    USERS_TEAM_SELECTOR(50),
    USERS_BY_ACTION_SELECTOR(51),
    USERS_BY_NAME_SELECTOR(52),
    USERS_ON_FURNI_SELECTOR(53),
    USERS_GROUP_SELECTOR(54),
    USERS_HANDITEM_SELECTOR(55),
    GIVE_VAR(69),
    REMOVE_VAR(73),
    CHANGE_VAR_VAL(74),
    FURNI_WITH_VAR_SELECTOR(75),
    USERS_WITH_VAR_SELECTOR(76),
    NEG_CALL_STACKS(86),
    NEG_SEND_SIGNAL(87),
    // Phase-2 chest/storage + transactions + place/remove-furni (action/selector codes).
    GIVE_CURRENCY_FROM_CHEST(99),
    GIVE_FURNI_FROM_CHEST(102),
    SCAN_CHEST_FURNI_BY_TYPE(103),
    INIT_TRANSACTION(104),
    CANCEL_TRANSACTION(105),
    PLACE_FURNI(106),
    REMOVE_FURNI(107),
    MOVE_FURNI_AS_GROUP(95),
    REMOTE_SELECTOR(96),
    // Negative-branch effects that reuse the SHOW_MESSAGE(7) client dialog (text). Distinct enum
    // constants so WiredEngine.isNegativeConditionEffect runs them only when conditions FAIL.
    NEG_SHOW_MESSAGE(7),
    NEG_LOG(7),
    SET_ROLLER_SPEED(88),
    BOT_DANCE(89),
    GIVE_POINTS_TYPE(90),
    GIVE_OR_TAKE_FURNI(91),
    PLAY_YOUTUBE(92),
    QUICK_BOPPER(93),
    SET_ROOM_AD(94),
    CHANGE_OPACITY(114),
    // Hotel-specific effects that reuse existing client dialogs (furni picker / message text).
    FURNI_COLLISION(0),
    ROLL_DICE(0),
    HIDE_FURNI(0),
    UNHIDE_FURNI(0),
    REMOVE_LOOK(7);

    public final int code;

    WiredEffectType(int code) {
        this.code = code;
    }
}
