package com.eu.habbo.plugin;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.annotation.Annotation;
import java.lang.reflect.AnnotatedElement;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.RecordComponent;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;

/**
 * Freezes the current plugin-visible wired surface that may be newer than the released Polaris ABI
 * baseline. Existing plugins can link to concrete wired boxes, packet classes and events as well as
 * the intended core interfaces, so internal extraction must leave these descriptors in place.
 *
 * <p>Regeneration is an explicit review action:
 *
 * <pre>
 * mvn test -Dtest=WiredPublicSurfaceCompatibilityTest \
 *   -Dpolaris.wired.api.regenerate=true
 * </pre>
 */
class WiredPublicSurfaceCompatibilityTest {

    private static final String REGENERATE_PROPERTY = "polaris.wired.api.regenerate";
    /**
     * The pom builds into target-build, not target. This used to read target/classes, which on a
     * working copy that once built the default way is a tree of stale classes: the snapshot then
     * described classes that had been deleted, and the test died on ClassNotFoundException.
     */
    private static final Path CLASSES_DIR = classesDirectory();

    private static Path classesDirectory() {
        Path built = Path.of("target-build", "classes");

        return Files.isDirectory(built) ? built : Path.of("target", "classes");
    }

    private static final Path CONTRACT =
            Path.of("src", "test", "resources", "wired-compatibility", "public-surface-v1.txt");

    private static final List<String> PACKAGE_ROOTS = List.of(
            "com/eu/habbo/habbohotel/wired",
            "com/eu/habbo/habbohotel/items/interactions/wired",
            "com/eu/habbo/messages/incoming/wired",
            "com/eu/habbo/messages/outgoing/wired",
            "com/eu/habbo/plugin/events/furniture/wired");

    private static final Set<String> EXACT_TYPES = Set.of(
            "com.eu.habbo.habbohotel.items.interactions.InteractionWired",
            "com.eu.habbo.habbohotel.items.interactions.InteractionWiredCondition",
            "com.eu.habbo.habbohotel.items.interactions.InteractionWiredEffect",
            "com.eu.habbo.habbohotel.items.interactions.InteractionWiredHighscore",
            "com.eu.habbo.habbohotel.items.interactions.InteractionWiredTrigger",
            "com.eu.habbo.habbohotel.rooms.WiredOpacityState",
            "com.eu.habbo.messages.outgoing.rooms.WiredFurniOpacityComposer",
            "com.eu.habbo.messages.outgoing.rooms.WiredMovementsComposer",
            "com.eu.habbo.plugin.WiredConfigurationBinder",
            "com.eu.habbo.plugin.events.users.UserWiredRewardReceived");

    @Test
    void currentWiredPublicSurfaceRemainsCompatible() throws Exception {
        assertTrue(Files.isDirectory(CLASSES_DIR), "Compiled classes not found: " + CLASSES_DIR);

        List<String> actual = snapshot();
        if (System.getProperty(REGENERATE_PROPERTY) != null) {
            Files.createDirectories(CONTRACT.getParent());
            Files.write(CONTRACT, actual, StandardCharsets.UTF_8);
            return;
        }

        assertTrue(
                Files.isRegularFile(CONTRACT),
                "Missing wired public-surface contract; regenerate with -D" + REGENERATE_PROPERTY + "=true");
        assertEquals(
                Files.readAllLines(CONTRACT, StandardCharsets.UTF_8),
                actual,
                "The current plugin-visible wired surface changed. Restore the old public/protected "
                        + "descriptor and delegate internally. Regenerate only after explicit compatibility review.");
    }

    private static List<String> snapshot() throws Exception {
        TreeSet<String> classNames = new TreeSet<>(EXACT_TYPES);
        for (String root : PACKAGE_ROOTS) {
            Path directory = CLASSES_DIR.resolve(root);
            if (!Files.isDirectory(directory)) {
                continue;
            }
            try (Stream<Path> paths = Files.walk(directory)) {
                paths.filter(path -> path.toString().endsWith(".class"))
                        .map(WiredPublicSurfaceCompatibilityTest::toClassName)
                        .forEach(classNames::add);
            }
        }

        List<String> lines = new ArrayList<>();
        lines.add("# Polaris current-tree wired plugin surface v1");
        lines.add("# Generated by WiredPublicSurfaceCompatibilityTest on JDK 25.");
        lines.add("# Review every diff; do not regenerate merely to make a refactor green.");
        lines.add("");

        ClassLoader loader = WiredPublicSurfaceCompatibilityTest.class.getClassLoader();
        for (String className : classNames) {
            Class<?> type = Class.forName(className, false, loader);
            if (!Modifier.isPublic(type.getModifiers())) {
                continue;
            }
            appendType(lines, type);
        }
        if (!lines.isEmpty() && lines.get(lines.size() - 1).isEmpty()) {
            lines.remove(lines.size() - 1);
        }
        return lines;
    }

    private static String toClassName(Path classFile) {
        return CLASSES_DIR
                .relativize(classFile)
                .toString()
                .replace(java.io.File.separatorChar, '.')
                .replaceFirst("\\.class$", "");
    }

    private static void appendType(List<String> lines, Class<?> type) {
        lines.add("TYPE " + typeDescriptor(type));
        appendAnnotations(lines, "TYPE-ANNOTATION " + type.getName(), type);

        if (type.isEnum()) {
            Object[] constants = type.getEnumConstants();
            for (int index = 0; index < constants.length; index++) {
                lines.add("ENUM " + type.getName() + " " + index + " " + ((Enum<?>) constants[index]).name());
            }
        }

        if (type.isRecord()) {
            for (RecordComponent component : type.getRecordComponents()) {
                lines.add("RECORD " + type.getName() + " " + component.getName() + ":"
                        + component.getGenericType().getTypeName());
                appendAnnotations(lines, "RECORD-ANNOTATION " + type.getName() + "#" + component.getName(), component);
            }
        }

        Arrays.stream(type.getDeclaredFields())
                .filter(WiredPublicSurfaceCompatibilityTest::isPluginVisible)
                .sorted(Comparator.comparing(Field::getName)
                        .thenComparing(field -> field.getType().getTypeName()))
                .forEach(field -> {
                    String subject = type.getName() + "#" + field.getName();
                    lines.add("FIELD " + modifiers(field.getModifiers()) + " " + subject + ":"
                            + field.getGenericType().getTypeName());
                    appendAnnotations(lines, "FIELD-ANNOTATION " + subject, field);
                });

        Arrays.stream(type.getDeclaredConstructors())
                .filter(WiredPublicSurfaceCompatibilityTest::isPluginVisible)
                .sorted(Comparator.comparing(WiredPublicSurfaceCompatibilityTest::constructorDescriptor))
                .forEach(constructor -> {
                    String subject = constructorDescriptor(constructor);
                    lines.add("CONSTRUCTOR " + modifiers(constructor.getModifiers()) + " " + subject);
                    appendAnnotations(lines, "CONSTRUCTOR-ANNOTATION " + subject, constructor);
                });

        Arrays.stream(type.getDeclaredMethods())
                .filter(WiredPublicSurfaceCompatibilityTest::isPluginVisible)
                .sorted(Comparator.comparing(WiredPublicSurfaceCompatibilityTest::methodDescriptor))
                .forEach(method -> {
                    String subject = methodDescriptor(method);
                    lines.add("METHOD " + modifiers(method.getModifiers()) + " " + subject);
                    appendAnnotations(lines, "METHOD-ANNOTATION " + subject, method);
                });

        lines.add("");
    }

    private static String typeDescriptor(Class<?> type) {
        List<String> parts = new ArrayList<>();
        parts.add(modifiers(type.getModifiers()));
        parts.add(type.getName());
        Type superclass = type.getGenericSuperclass();
        if (superclass != null) {
            parts.add("extends");
            parts.add(superclass.getTypeName());
        }
        Type[] interfaces = type.getGenericInterfaces();
        if (interfaces.length > 0) {
            parts.add("implements");
            parts.add(typeList(interfaces));
        }
        return String.join(" ", parts);
    }

    private static String constructorDescriptor(Constructor<?> constructor) {
        return constructor.getDeclaringClass().getName() + "(" + typeList(constructor.getGenericParameterTypes())
                + ") throws " + typeList(constructor.getGenericExceptionTypes());
    }

    private static String methodDescriptor(Method method) {
        return method.getDeclaringClass().getName() + "#" + method.getName() + "("
                + typeList(method.getGenericParameterTypes()) + "):"
                + method.getGenericReturnType().getTypeName()
                + " throws " + typeList(method.getGenericExceptionTypes());
    }

    private static String typeList(Type[] types) {
        return Arrays.stream(types)
                .map(Type::getTypeName)
                .reduce((left, right) -> left + "," + right)
                .orElse("-");
    }

    private static String modifiers(int modifiers) {
        String value = Modifier.toString(modifiers);
        return value.isEmpty() ? "package" : value;
    }

    private static boolean isPluginVisible(Field field) {
        return isPluginVisible(field.getModifiers());
    }

    private static boolean isPluginVisible(Constructor<?> constructor) {
        return isPluginVisible(constructor.getModifiers());
    }

    private static boolean isPluginVisible(Method method) {
        return isPluginVisible(method.getModifiers());
    }

    private static boolean isPluginVisible(int modifiers) {
        return Modifier.isPublic(modifiers) || Modifier.isProtected(modifiers);
    }

    private static void appendAnnotations(List<String> lines, String subject, AnnotatedElement element) {
        Arrays.stream(element.getDeclaredAnnotations())
                .sorted(Comparator.comparing(
                        annotation -> annotation.annotationType().getName()))
                .map(WiredPublicSurfaceCompatibilityTest::annotationDescriptor)
                .forEach(annotation -> lines.add(subject + " " + annotation));
    }

    private static String annotationDescriptor(Annotation annotation) {
        return annotation.annotationType().getName() + annotationValues(annotation);
    }

    private static String annotationValues(Annotation annotation) {
        Collection<String> values = Arrays.stream(annotation.annotationType().getDeclaredMethods())
                .sorted(Comparator.comparing(Method::getName))
                .map(method -> method.getName() + "=" + invokeAnnotationMember(annotation, method))
                .toList();
        return values.isEmpty() ? "" : values.toString();
    }

    private static String invokeAnnotationMember(Annotation annotation, Method method) {
        try {
            Object value = method.invoke(annotation);
            if (value != null && value.getClass().isArray()) {
                if (value instanceof Object[] objects) {
                    return Arrays.deepToString(objects);
                }
                int length = java.lang.reflect.Array.getLength(value);
                List<String> entries = new ArrayList<>(length);
                for (int index = 0; index < length; index++) {
                    entries.add(String.valueOf(java.lang.reflect.Array.get(value, index)));
                }
                return entries.toString();
            }
            return String.valueOf(value);
        } catch (ReflectiveOperationException exception) {
            throw new IllegalStateException("Cannot read annotation member " + method, exception);
        }
    }
}
